schema converter improvements
zimnx/YamlSchemaToGoStruct pull request #1
Opened 2017-08-02 09:03 UTC by jkmar

Schema converter improvements:
-added support for schema inheritance and parents
-changed command line client
-changed error handling
-fixed double tags

2017-08-07 10:03 UTC, zimnx requested changes

2017-08-07 10:03 UTC, zimnx commented on item/object.go
> +func (item *Object) IsObject() bool {
Remove it, it's used only in tests and shouldn't belong to Item interface.

2017-08-07 10:03 UTC, zimnx commented on item/item.go
> +	Type(string) string
comments about each method and parameter would be nice

2017-08-07 15:36 UTC, jkmar commented
@zimnx @przemyslaw-dobrowolski-cl @p-kozlowski @michalzurawski
Please review.

2017-08-07 16:10 UTC, michalzurawski commented on item/array.go
> +func (item *Array) Type(suffix string) string {
Could you please use a different name for the variable than 'item' as it is the package name?

2017-08-11 12:56 UTC, zimnx approved these changes

2017-08-11 12:58 UTC, zimnx commented
Very good job, code is well designed

2017-08-11 12:58 UTC, merged